name = "Console-idated"
author = "S_N00B"
version = "1.3.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3b8d6623b64cf4948473cefd52f75436a99b4eb2c8cbf9dc08c0cefadb41fe05"

[versions]
fabric = "0.16.7"
minecraft = "1.20.4"

[options]
acceptable-game-versions = ["1.20.1", "1.20.4"]
