name = "Console-idated"
author = "S_N00B"
version = "1.2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eb0358565ef7c77bdbf43c595f5e3b5e4706d619b9601a71f3785defa60a1c83"

[versions]
fabric = "0.16.0"
minecraft = "1.20.4"

[options]
acceptable-game-versions = ["1.20.1", "1.20.4"]
