hideType = "RELOADING"
rgbProgress = false
forceClose = false
blockOverlay = false
miniRender = false
type = "PROGRESS"
reloadText = "Edit in config!"
resetResources = true
reInitScreen = false
removeOverlayAtEnd = true
earlyPackStatusSend = false
doubleLoad = "FORCE_LOAD"
animationSpeed = 1000.0
aprilFool = "ON_APRIL"
